### ISSUE TITLE
entering "(, +, *"  causing an error

### ISSUE THREAD

**Issue by Ilaiwi** [OoDeLally/formik-undo#4]
when writing any of the characters "(, +, *" in a formik input cases a crash. This is related to the `preventWordCutting` where when I turned it off I didn't have the issue anymore.

![2020-08-25 11 02 36](https://user-images.githubusercontent.com/10817089/91148595-8c4b2400-e6c2-11ea-8567-7bdc92c06484.gif)

Thanks for the great library.

**Comment by OoDeLally** [comment]
Hi @Ilaiwi , thanks for reporting the issue.
1.5.2 should fix that.
https://github.com/OoDeLally/formik-undo/commit/163b8fb7ee4414ba4af6162217a580f5baa59541
